# Workflow to run all tests

name: Functional tests

on:
  push:
    branches: [ "main" ]
    paths-ignore: ['examples/**']
  pull_request:
    branches: [ "main" ]
    paths-ignore: ['examples/**']

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e . 
        pip install html2text
        cd tests
        echo "Installing CopasiSE"
        wget -q http://cuprum.cam.uchc.edu/copasi/CopasiSE.gz
        gunzip CopasiSE.gz
        chmod a+x CopasiSE
    - name: run tests
      run: |
        cd tests
        ./run_all_tests.sh
