# Workflow to run all tests

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install html2text
        #cd tests
        #wget https://github.com/copasi/COPASI/releases/download/Build-288/COPASI-4.43.288-Source.tar.gz
        #tar -xvf COPASI-4.43.288-AllSE.tar.gz
        #ln -s COPASI-4.43.288-AllSE/Linux/CopasiSE .
    - name: run tests
      run: |
        cd tests
        ./run_all_tests.sh
